// <auto-generated />
using BarinakTakip.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BarinakTakip.Migrations
{
    [DbContext(typeof(ApplicationConnectionDb))]
    [Migration("20220530194623_Initial-V7")]
    partial class InitialV7
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BarinakTakip.Models.Barinak", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Ad")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Adres")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Il")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Ilce")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Kapasite")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Barinak");
                });

            modelBuilder.Entity("BarinakTakip.Models.Hayvan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Ad")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("BarinakId")
                        .HasColumnType("int");

                    b.Property<string>("Saglik")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Tur")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Yas")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("altTur")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Hayvan");
                });

            modelBuilder.Entity("BarinakTakip.Models.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Ad")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Mail")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Parola")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Soyad")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Kullanici");
                });
#pragma warning restore 612, 618
        }
    }
}
